id: P004243
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS16793
  title: བསྟན་རྒྱས་སྨོན་ལམ་དང་རྩོད་སྤོང་སྨྲ་སེང་།
  author: ''
  volumes:
    76033bfd173044c2bc3c2e6e1066eb57:
      image_group_id: I8LS16802
      title: ''
      volume_number: 1
      total_pages: 24
      base_file: v001.txt
